M48
; DRILL file {KiCad 9.0.7} date 2026-02-27T11:32:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-27T11:32:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X182.22Y-118.5
X188.0Y-118.5
T2
X163.0Y-121.5
X187.5Y-98.0
X211.0Y-121.5
M30
